Repository DeliverBle/deliverble-frontend, pull requests merged in 2022-07, with the labels that each got.

#2 [setting] 프로젝트 초기 세팅
  .babelrc
  .eslintrc.json
  .gitignore
  .prettierrc
  README.md
  next-env.d.ts
  next.config.js
  package.json
  public/favicon.ico
  public/vercel.svg
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/styles/color.ts
  src/styles/fontStyle.ts
  src/styles/globalStyle.ts
  tsconfig.json
  yarn.lock
Labels: 🎉 init

#7 [review] 복습페이지 퍼블리싱
  public/assets/icons/ic_script.svg
  public/assets/icons/index.ts
  src/components/Review/HeadlineContainer.tsx
  src/components/Review/VideoContainer.tsx
  src/pages/review.tsx
Labels: 💅 design, ✨ feat

#14 [learn] 셀렉트박스 컴포넌트
  public/assets/icons/ic_checked_box.svg
  public/assets/icons/ic_empty_box.svg
  public/assets/icons/index.ts
  src/components/learn/SelectBox.tsx
  src/pages/learn.tsx
Labels: 💅 design, ✨ feat

#15 [learn_detail] 학습 기능 설명 모달창
  public/assets/icons/ic_guide.svg
  public/assets/icons/ic_guide_highlight.svg
  public/assets/icons/ic_guide_spacing.svg
  public/assets/icons/ic_x_button.svg
  public/assets/icons/index.ts
  src/components/common/NewsList.tsx
  src/components/learnDetail/GuideModal.tsx
  src/components/review/HeadlineContainer.tsx
  src/components/review/VideoContainer.tsx
  src/pages/home.tsx
  src/pages/learn/[id].tsx
Labels: 💅 design, ✨ feat, 🧰 asset

#13 [common] 네비게이션 바 컴포넌트
  src/components/common/NavigationBar.tsx
  src/pages/index.tsx
  src/styles/globalStyle.ts
Labels: 💅 design, ✨ feat

#24 [common] API 데이터 서비스 인터페이스
  src/pages/api/hello.ts
  src/pages/learn/[id].tsx
  src/services/api/index.ts
  src/services/api/learn-detail.ts
  src/services/api/types/learn-detail.ts
  src/services/mock/learn-detail.data.ts
  src/services/mock/learn-detail.ts
Labels: ✨ feat

#19 [common] 즐겨찾기 퍼블리싱
  public/assets/icons/ic_like_clicked.svg
  public/assets/icons/ic_like_default.svg
  public/assets/icons/ic_like_hover.svg
  public/assets/icons/index.ts
  src/components/common/Like.tsx
  src/components/common/NewsList.tsx
  src/pages/404.tsx
Labels: 💅 design, ✨ feat, 🧰 asset

#22 [common] 푸터 퍼블리싱
  public/assets/icons/ic_logo_footer.svg
  public/assets/icons/ic_social.svg
  public/assets/icons/index.ts
  src/components/common/Footer.tsx
  src/pages/home.tsx
Labels: 💅 design, 🧰 asset

#20 [learn] 셀렉트박스 외부 영역 클릭 시 처리
  src/components/learn/SelectBox.tsx
  src/pages/learn/index.tsx
Labels: ✨ feat

#27 [common] 로그인 모달 퍼블리싱
  public/assets/icons/ic_kakao.svg
  public/assets/icons/ic_microphone.svg
  public/assets/icons/index.ts
  src/components/common/NavigationBar.tsx
  src/components/login/LoginModal.tsx
  src/components/login/OAuth.ts
Labels: 💅 design, ✨ feat, 🧰 asset

#32 [common] 홈 뷰 추천 영상 조회 mock API 연결
  next.config.js
  src/components/common/Like.tsx
  src/components/common/NewsList.tsx
  src/pages/404.tsx
  src/pages/home.tsx
  src/services/api/home.ts
  src/services/api/index.ts
  src/services/api/types/home.ts
  src/services/mock/home.data.ts
  src/services/mock/home.ts
Labels: ✨ feat

#33 [learn_detail] 학습 상세 페이지에 영상, 메모, 스크립트 넣기
  package.json
  public/assets/icons/ic_announce.svg
  public/assets/icons/ic_highlighter.svg
  public/assets/icons/ic_memo.svg
  public/assets/icons/ic_spacing.svg
  public/assets/icons/index.ts
  src/pages/learn/[id].tsx
  src/services/api/types/learn-detail.ts
  src/services/mock/learn-detail.data.ts
  yarn.lock
Labels: 💅 design, ✨ feat, 🧰 asset

#31 [review] 복습페이지 EMPTY 뷰
  public/assets/images/img_review_empty.svg
  public/assets/images/index.ts
  src/components/review/Empty.tsx
  src/pages/review.tsx
Labels: 💅 design, 🧰 asset

#29 [landing] 랜딩페이지
  public/assets/icons/ic_deliverble_blue.svg
  public/assets/icons/ic_deliverble_white.svg
  public/assets/icons/index.ts
  public/assets/images/img_landing_bubble.svg
  public/assets/images/img_landing_ear.svg
  public/assets/images/img_landing_first_bg.svg
  public/assets/images/img_landing_fist.svg
  public/assets/images/img_landing_last_bg.svg
  public/assets/images/img_landing_mic.svg
  public/assets/images/img_landing_second_bg.svg
  public/assets/images/index.ts
  public/assets/lottie/index.ts
  public/assets/lottie/step1.json
  public/assets/lottie/step2.json
  public/assets/lottie/step3.json
  src/components/landing/Nav.tsx
  src/components/landing/ScrollControl.tsx
  src/components/landing/SliderContainer.tsx
  src/components/landing/useSlideObserver.ts
  src/pages/index.tsx
  src/styles/fontStyle.ts
Labels: 💅 design, ✨ feat, 🧰 asset, 🪄 chore

#37 [landing] 로그인 모달
  src/components/landing/Nav.tsx
Labels: ✨ feat

#38 [common] 검색 엔진 최적화 작업
  public/assets/images/img_thumbnail.png
  src/components/common/SEO.tsx
  src/pages/404.tsx
  src/pages/_document.tsx
  src/pages/home.tsx
  src/pages/index.tsx
  src/pages/learn/[id].tsx
  src/pages/learn/index.tsx
  src/pages/review.tsx
Labels: 🪄 chore

#41 [learn_detail] 하이라이트 모달 컴포넌트 구현
  public/assets/icons/ic_alert.svg
  public/assets/icons/index.ts
  src/components/learnDetail/HighlightModal.tsx
  src/pages/learn/[id].tsx
Labels: 💅 design, ✨ feat

#42 [learn] 조건에 맞는 뉴스 조회
  public/assets/icons/ic_double_left_arrow.svg
  public/assets/icons/ic_double_right_arrow.svg
  public/assets/icons/ic_left_arrow.svg
  public/assets/icons/ic_right_arrow.svg
  public/assets/icons/index.ts
  src/components/common/SEO.tsx
  src/components/landing/SliderContainer.tsx
  src/components/learn/SelectBox.tsx
  src/pages/_document.tsx
  src/pages/learn/index.tsx
  src/services/api/index.ts
  src/services/api/learn.ts
  src/services/api/types/learn.ts
  src/services/mock/learn.data.ts
  src/services/mock/learn.ts
Labels: ✨ feat

#45 [common] 푸터 링크 연결
  src/components/common/Footer.tsx
  src/styles/fontStyle.ts
Labels: 💅 design, 🪄 chore

#48 [learn, learn_detail] remote 폴더 사용해서 실서버 API 연결
  src/components/learn/SelectBox.tsx
  src/pages/learn/index.tsx
  src/services/api/index.ts
  src/services/api/types/learn-detail.ts
  src/services/api/types/learn.ts
  src/services/remote/base.ts
  src/services/remote/learn-detail.ts
  src/services/remote/learn.ts
Labels: ✨ feat

#53 [learn_detail] 학습 상세 페이지 즐겨찾기
  src/components/common/Like.tsx
  src/components/common/NewsList.tsx
  src/pages/learn/[id].tsx
Labels: 💅 design, ✨ feat

#51 [learn_detail] 메모 조회, 수정, 삭제 퍼블리싱
  public/assets/icons/ic_check_button.svg
  public/assets/icons/ic_dot_default.svg
  public/assets/icons/ic_dot_hover.svg
  public/assets/icons/ic_memo_x_button.svg
  public/assets/icons/index.ts
  public/assets/images/img_memo_empty.svg
  public/assets/images/index.ts
  src/components/common/Like.tsx
  src/components/common/NewsList.tsx
  src/components/learnDetail/memo/EmptyMemo.tsx
  src/components/learnDetail/memo/Memo.tsx
  src/components/learnDetail/memo/MemoEditForm.tsx
  src/components/learnDetail/memo/MemoList.tsx
  src/components/learnDetail/memo/MemoPopup.tsx
  src/components/learnDetail/memo/MemoPopupButton.tsx
  src/pages/learn/[id].tsx
  src/services/api/learn-detail.ts
  src/services/api/types/learn-detail.ts
  src/services/mock/learn-detail.data.ts
  src/services/mock/learn-detail.ts
  src/services/remote/learn-detail.ts
  src/styles/color.ts
  src/styles/fontStyle.ts
Labels: 💅 design, ✨ feat, 🧰 asset

#57 [home] 홈 뷰 추천 영상 조회 실서버 API 붙이기
  src/pages/home.tsx
  src/services/api/home.ts
  src/services/api/index.ts
  src/services/api/types/home.ts
  src/services/mock/home.data.ts
  src/services/mock/home.ts
  src/services/remote/home.ts
Labels: ✨ feat

#55 [learn_detail] confirm창 컴포넌트 구현
  src/components/learnDetail/ConfirmModal.tsx
  src/pages/learn/[id].tsx
Labels: 💅 design, ✨ feat

#58 [learn_detail] 끊어읽기, 하이라이트 기능 구현
  public/assets/icons/ic_highlighter_clicked.svg
  public/assets/icons/ic_highlighter_default.svg
  public/assets/icons/ic_highlighter_hover.svg
  public/assets/icons/ic_spacing_clicked.svg
  public/assets/icons/ic_spacing_default.svg
  public/assets/icons/ic_spacing_hover.svg
  public/assets/icons/index.ts
  src/components/learnDetail/ScriptEdit.tsx
  src/pages/learn/[id].tsx
Labels: 💅 design, ✨ feat, 🧰 asset

#62 [learn] 페이지네이션
  public/assets/icons/ic_double_left_arrow_hover.svg
  public/assets/icons/ic_double_right_arrow_hover.svg
  public/assets/icons/ic_left_arrow_hover.svg
  public/assets/icons/ic_right_arrow_hover.svg
  public/assets/icons/index.ts
  src/components/common/Pagination.tsx
  src/pages/learn/index.tsx
Labels: 💅 design, ✨ feat

#64 [learn_detail] 하이라이트 우클릭 컨텍스트 메뉴
  src/components/learnDetail/ContextMenu.tsx
  src/components/learnDetail/ScriptEdit.tsx
  src/components/learnDetail/memo/MemoPopup.tsx
  src/pages/home.tsx
  src/pages/learn/[id].tsx
Labels: 💅 design, ✨ feat

#65 [learn_detail] confirm창 컴포넌트 리팩토링
  src/components/learnDetail/ConfirmModal.tsx
  src/pages/learn/[id].tsx
Labels: 🔨 refactor

#69 [review] 내 즐겨찾기 기록
  .gitignore
  src/components/common/Footer.tsx
  src/components/review/Empty.tsx
  src/components/review/HeadlineContainer.tsx
  src/components/review/VideoContainer.tsx
  src/pages/review.tsx
  src/services/api/index.ts
  src/services/api/review.ts
  src/services/api/types/review.ts
  src/services/mock/review.data.ts
  src/services/mock/review.ts
Labels: ✨ feat

#70 [common] 네비게이션바 로그인 처리
  public/assets/icons/ic_btn_mypage.svg
  public/assets/icons/index.ts
  src/components/common/NavigationBar.tsx
  src/components/login/LoginModal.tsx
  src/components/login/OAuth.ts
  src/hooks/useLoginUser.ts
  src/pages/auth/kakao.tsx
  src/pages/index.tsx
  src/services/api/login-user.ts
  src/services/api/types/user.ts
  src/services/remote/base.ts
  src/stores/login-user.ts
Labels: ✨ feat, 🧰 asset

#73 [learn_deatil] 메모 추가 퍼블리싱
  src/components/learnDetail/ConfirmModal.tsx
  src/components/learnDetail/ContextMenu.tsx
  src/components/learnDetail/ScriptEdit.tsx
  src/components/learnDetail/memo/Memo.tsx
  src/components/learnDetail/memo/MemoForm.tsx
  src/components/learnDetail/memo/MemoList.tsx
  src/components/learnDetail/memo/MemoPopup.tsx
  src/components/learnDetail/memo/MemoPopupButton.tsx
  src/pages/404.tsx
  src/pages/auth/kakao.tsx
  src/pages/learn/[id].tsx
  src/services/api/learn-detail.ts
  src/services/api/types/learn-detail.ts
  src/services/mock/learn-detail.data.ts
  src/services/mock/learn-detail.ts
  src/services/remote/learn-detail.ts
Labels: ✨ feat

#74 [common] 로그아웃 처리 및 프로필 모달 구현
  public/assets/icons/ic_logout.svg
  public/assets/icons/index.ts
  src/components/common/NavigationBar.tsx
  src/components/common/ProfileModal.tsx
Labels: 💅 design, ✨ feat, 🧰 asset

#67 [learn_detail] 하이라이트, 끊어읽기 예외처리, 하이라이트 중복 모달, 인덱스 가져오기
  src/components/landing/ScrollControl.tsx
  src/components/learnDetail/ScriptEdit.tsx
  src/pages/learn/[id].tsx
  src/services/api/types/learn-detail.ts
Labels: ✨ feat

#80 [common] 프로필 모달 디자인 수정
  src/components/common/ProfileModal.tsx
Labels: 💅 design

#81 [common] 로그인 필요한 기능 접근 시 로그인 모달 띄우기
  src/components/common/ProfileModal.tsx
  src/pages/learn/[id].tsx
Labels: ✨ feat

#84 [common] 즐겨찾기 실서버 API 연결
  src/components/common/Like.tsx
  src/components/common/NewsList.tsx
  src/components/learnDetail/ConfirmModal.tsx
  src/pages/auth/kakao.tsx
  src/pages/learn/[id].tsx
  src/services/api/index.ts
  src/services/api/like.ts
  src/services/api/types/home.ts
  src/services/api/types/like.ts
  src/services/mock/like.data.ts
  src/services/remote/like.ts
Labels: ✨ feat

#85 [common] 즐겨찾기 실서버 API 연결
  src/components/common/Like.tsx
  src/components/common/NewsList.tsx
  src/components/review/VideoContainer.tsx
  src/pages/home.tsx
  src/pages/learn/[id].tsx
  src/pages/review.tsx
  src/services/api/index.ts
  src/services/api/like.ts
Labels: 🐛 fix, 🔨 refactor

#90 [common] 여러 페이지 리팩터링
  src/components/common/NewsList.tsx
  src/components/learnDetail/ScriptEdit.tsx
  src/components/learnDetail/VideoDetail.tsx
  src/pages/learn/[id].tsx
  src/pages/review.tsx
Labels: 🔨 refactor
