Repository DeliverBle/deliverble-frontend, pull requests merged in 2022-09, with the labels that each got.

#119 [common] 한글 로고 관련 디자인 QA 반영
  public/assets/icons/ic_deliverble_blue.svg
  public/assets/icons/ic_deliverble_nav.svg
  public/assets/icons/ic_deliverble_white.svg
  public/assets/icons/ic_logo_footer.svg
  public/assets/icons/index.ts
  public/assets/images/img_logo.svg
  public/assets/images/index.ts
  src/components/common/Footer.tsx
  src/components/common/NavigationBar.tsx
  src/components/landing/Nav.tsx
  src/components/login/LoginModal.tsx
Labels: 💅 design, 🧰 asset

#124 [learn_detail] 학습 기능 설명 모달창 ver.2 반영
  public/assets/icons/ic_guide_highlight.svg
  public/assets/icons/ic_guide_memo.svg
  public/assets/icons/ic_guide_script.svg
  public/assets/icons/ic_guide_spacing.svg
  public/assets/icons/index.ts
  src/components/learnDetail/GuideModal.tsx
  src/styles/fontStyle.ts
Labels: 💅 design, 🧰 asset

#125 [common] 뉴스 리스트 반응형 구현
  src/components/common/Footer.tsx
  src/components/common/NewsList.tsx
  src/pages/home.tsx
Labels: 💅 design

#129 [common] 푸터 반응형 구현
  src/components/common/Footer.tsx
Labels: 💅 design

#127 [common] 로그인 목데이터로 구현 및 실서버 연결
  src/components/common/NavigationBar.tsx
  src/components/common/NewsList.tsx
  src/components/common/ProfileModal.tsx
  src/components/learnDetail/memo/MemoForm.tsx
  src/components/login/OAuth.ts
  src/hooks/useLoginUser.ts
  src/pages/auth/callback/kakao.tsx
  src/pages/auth/kakao.tsx
  src/pages/index.tsx
  src/services/api/index.ts
  src/services/api/login-user.ts
  src/services/api/types/user.ts
  src/services/mock/user.data.ts
  src/services/mock/user.ts
  src/services/remote/login-user.ts
  src/stores/login-user.ts
  src/stores/loginState.ts
Labels: ✨ feat, 🔨 refactor
