Repository DeliverBle/deliverble-frontend, pull requests merged in 2022-12, with the labels that each got.

#147 [learn_detail] 메모 서버 마이그레이션 반영
  public/assets/icons/ic_inactive_check_button.svg
  public/assets/icons/ic_not_allowed_cursor.svg
  public/assets/icons/index.ts
  src/components/learnDetail/ConfirmModal.tsx
  src/components/learnDetail/ContextMenu.tsx
  src/components/learnDetail/memo/Memo.tsx
  src/components/learnDetail/memo/MemoDotButton.tsx
  src/components/learnDetail/memo/MemoDropdown.tsx
  src/components/learnDetail/memo/MemoForm.tsx
  src/components/learnDetail/memo/MemoList.tsx
  src/pages/learn/[id].tsx
  src/services/api/learn-detail.ts
  src/services/api/types/learn-detail.ts
  src/services/mock/learn-detail.data.ts
  src/services/mock/learn-detail.ts
  src/services/remote/base.ts
  src/services/remote/learn-detail.ts
  src/utils/constant.ts
  tsconfig.json
Labels: 💅 design, ✨ feat, 🎨 style, 🔨 refactor

#149 [learn_detail] 스크립트 생성/삭제/수정 API 연결
  src/components/learnDetail/ConfirmModal.tsx
  src/components/learnDetail/ScriptEdit.tsx
  src/components/learnDetail/ScriptTitle.tsx
  src/pages/learn/[id].tsx
  src/pages/learn/index.tsx
  src/services/api/learn-detail.ts
  src/services/api/types/learn-detail.ts
  src/services/mock/learn-detail.data.ts
  src/services/mock/learn-detail.ts
  src/services/remote/learn-detail.ts
  src/utils/constant.ts
Labels: ✨ feat

#153 [common] 로그인 여부에 따른 API 분기 처리
  public/assets/images/img_thumbnail.png
  public/assets/images/img_twitter_thumbnail.png
  public/assets/images/img_twitter_thumnail.png
  src/pages/_app.tsx
  src/pages/home.tsx
  src/pages/learn/index.tsx
  src/services/api/home.ts
  src/services/api/learn.ts
  src/services/api/types/home.ts
  src/services/api/types/learn.ts
  src/services/mock/home.ts
  src/services/mock/learn.ts
  src/services/remote/home.ts
  src/services/remote/learn.ts
Labels: 🐛 fix

#154 [common] GA, Hotjar 도입
  package.json
  src/pages/_app.tsx
  src/utils/constant.ts
  src/utils/gtag.ts
  yarn.lock
Labels: ✨ feat

#157 [common] 푸터 디자인 변경
  public/assets/icons/ic_deliverble_blue.svg
  public/assets/icons/ic_social.svg
  src/components/common/Footer.tsx
Labels: 💅 design, 🧰 asset

#155 [home, learn_detail] 스피치 가이드 구현
  package-lock.json
  public/assets/icons/ic_speech_guide_corner.svg
  public/assets/icons/ic_speech_guide_info.svg
  public/assets/icons/ic_speech_guide_logo.svg
  public/assets/icons/index.ts
  src/components/common/Footer.tsx
  src/components/common/NavigationBar.tsx
  src/components/common/NewsList.tsx
  src/components/learnDetail/memo/Memo.tsx
  src/components/review/VideoContainer.tsx
  src/pages/home.tsx
  src/pages/learn/[id].tsx
  src/pages/learn/index.tsx
  src/services/api/home.ts
  src/services/api/learn-detail.ts
  src/services/api/types/home.ts
  src/services/api/types/learn-detail.ts
  src/services/api/types/learn.ts
  src/services/api/types/review.ts
  src/services/mock/home.data.ts
  src/services/mock/home.ts
  src/services/mock/learn-detail.data.ts
  src/services/mock/learn-detail.ts
  src/services/mock/learn.data.ts
  src/services/mock/review.data.ts
  src/services/remote/home.ts
  src/services/remote/learn-detail.ts
  src/services/remote/learn.ts
  src/services/remote/review.ts
  src/stores/newsState.ts
  src/styles/fontStyle.ts
  src/utils/constant.ts
  yarn.lock
Labels: 💅 design, ✨ feat, 🧰 asset

#159 [learn_detail] 녹음 저장 기능 구현
  public/assets/icons/ic_record_mic_active.svg
  public/assets/icons/ic_record_mic_default.svg
  public/assets/icons/ic_record_start.svg
  public/assets/icons/ic_record_stop.svg
  public/assets/icons/index.ts
  src/components/learnDetail/record/RecordStatusBar.tsx
  src/pages/learn/[id].tsx
  src/services/api/learn-detail.ts
  src/services/api/types/learn-detail.ts
  src/services/mock/learn-detail.data.ts
  src/services/mock/learn-detail.ts
  src/services/remote/base.ts
  src/services/remote/learn-detail.ts
  yarn.lock
Labels: 💅 design, ✨ feat, 🧰 asset

#161 [home] 배너 슬라이드 기능 구현
  package.json
  public/assets/icons/ic_left_arrow_white.svg
  public/assets/icons/ic_right_arrow_white.svg
  public/assets/icons/index.ts
  public/assets/images/img_banner_ver1_background.png
  public/assets/images/img_banner_ver1_deco1.png
  public/assets/images/img_banner_ver1_deco2.png
  public/assets/images/img_banner_ver2_background.png
  public/assets/images/img_banner_ver2_deco.png
  public/assets/images/img_banner_ver3_background.png
  public/assets/images/img_banner_ver3_deco.png
  public/assets/images/img_big_banner_mic.png
  public/assets/images/img_medium_banner_mic.png
  public/assets/images/index.ts
  src/components/common/BannerSlider.tsx
  src/pages/_document.tsx
  src/pages/home.tsx
  src/utils/constant.ts
  yarn.lock
Labels: 💅 design, ✨ feat, 🧰 asset

#170 [learn_detail] 비슷한 영상 추천
  src/components/common/NewsList.tsx
  src/pages/learn/[id].tsx
  src/services/api/learn-detail.ts
  src/services/mock/learn-detail.ts
  src/services/remote/learn-detail.ts
Labels: 💅 design, ✨ feat, 🧰 asset

#168 [review] 내 학습기록
  src/components/review/Empty.tsx
  src/components/review/VideoContainer.tsx
  src/pages/review.tsx
  src/services/api/review.ts
  src/services/api/types/review.ts
  src/services/mock/review.data.ts
  src/services/mock/review.ts
  src/services/remote/review.ts
Labels: ✨ feat

#163 [learn_detail] 녹음 탭 퍼블리싱 및 녹음 불러오기, 다운로드, 수정, 삭제 기능
  public/assets/icons/ic_memo.svg
  public/assets/icons/ic_record_empty.svg
  public/assets/icons/ic_record_pause_active.svg
  public/assets/icons/ic_record_pause_default.svg
  public/assets/icons/ic_record_play_active.svg
  public/assets/icons/ic_record_play_default.svg
  public/assets/icons/ic_record_play_unactivated.svg
  public/assets/icons/index.ts
  src/components/learnDetail/ScriptTitle.tsx
  src/components/learnDetail/record/EmptyRecord.tsx
  src/components/learnDetail/record/RecordDotButton.tsx
  src/components/learnDetail/record/RecordDropdown.tsx
  src/components/learnDetail/record/RecordLog.tsx
  src/components/learnDetail/record/RecordStatusBar.tsx
  src/pages/learn/[id].tsx
  src/services/api/learn-detail.ts
  src/services/api/types/learn-detail.ts
  src/services/mock/learn-detail.data.ts
  src/services/mock/learn-detail.ts
  src/services/remote/learn-detail.ts
  src/styles/fontStyle.ts
Labels: 💅 design, ✨ feat

#173 [learn_detail] 하이라이트, 메모 연결 부분 수정
  src/components/learnDetail/ScriptEdit.tsx
  src/components/learnDetail/memo/MemoForm.tsx
  src/components/learnDetail/memo/MemoList.tsx
  src/pages/learn/[id].tsx
  src/services/api/types/learn-detail.ts
  src/services/mock/learn-detail.data.ts
  src/services/remote/learn-detail.ts
  src/utils/constant.ts
Labels: ✨ feat, 🔨 refactor
