Repository DeliverBle/deliverble-frontend, pull requests merged in 2022-08, with the labels that each got.

#91 [common] 불필요한 코드 정리
  src/components/common/NavigationBar.tsx
  src/components/learnDetail/ScriptEdit.tsx
Labels: 🪄 chore

#95 [common] 디자인 QA 일부 반영
  public/assets/icons/ic_arrow.svg
  public/assets/icons/ic_guide_clicked.svg
  public/assets/icons/ic_guide_hover.svg
  public/assets/icons/index.ts
  src/components/common/NewsList.tsx
  src/components/common/Pagination.tsx
  src/components/learn/SelectBox.tsx
  src/components/review/Empty.tsx
  src/components/review/VideoContainer.tsx
  src/pages/home.tsx
  src/pages/learn/[id].tsx
  src/pages/learn/index.tsx
  src/pages/review.tsx
Labels: 🪄 chore

#96 [landing] smooth 속성 추가
  src/components/landing/ScrollControl.tsx
  src/components/landing/SliderContainer.tsx
  src/components/landing/useSlideObserver.ts
  src/pages/index.tsx
Labels: ✨ feat, 🔨 refactor

#99 [learn_detail] 데모데이 시연용 목데이터, 가공 코드 삭제
  src/components/learnDetail/ScriptEdit.tsx
  src/pages/learn/[id].tsx
Labels: 🪄 chore

#97 [common] 로그인 성공 시 이전 페이지로 이동
  src/pages/_app.tsx
  src/pages/auth/kakao.tsx
  src/pages/learn/[id].tsx
Labels: 🐛 fix, 🔨 refactor

#101 [learn, learn_detail] 스타일 분리 작업
  src/components/learn/SelectBox/index.tsx
  src/components/learn/SelectBox/style.ts
  src/components/learnDetail/ConfirmModal/index.tsx
  src/components/learnDetail/ConfirmModal/style.ts
  src/components/learnDetail/ContextMenu/index.tsx
  src/components/learnDetail/ContextMenu/style.ts
  src/components/learnDetail/GuideModal/index.tsx
  src/components/learnDetail/GuideModal/style.ts
  src/components/learnDetail/HighlightModal.tsx
  src/components/learnDetail/HighlightModal/index.tsx
  src/components/learnDetail/HighlightModal/style.ts
  src/components/learnDetail/ScriptEdit/index.tsx
  src/components/learnDetail/ScriptEdit/style.ts
  src/components/learnDetail/VideoDetail.tsx
  src/components/learnDetail/VideoDetail/index.tsx
  src/components/learnDetail/VideoDetail/style.ts
Labels: 🪄 chore

#107 [learn, learn_detail] 스타일 분리 작업 되돌리기
  src/components/learn/SelectBox.tsx
  src/components/learn/SelectBox/style.ts
  src/components/learnDetail/ConfirmModal.tsx
  src/components/learnDetail/ConfirmModal/index.tsx
  src/components/learnDetail/ContextMenu.tsx
  src/components/learnDetail/ContextMenu/index.tsx
  src/components/learnDetail/GuideModal.tsx
  src/components/learnDetail/GuideModal/style.ts
  src/components/learnDetail/HighlightModal.tsx
  src/components/learnDetail/HighlightModal/index.tsx
  src/components/learnDetail/HighlightModal/style.ts
  src/components/learnDetail/ScriptEdit.tsx
  src/components/learnDetail/ScriptEdit/style.ts
  src/components/learnDetail/VideoDetail.tsx
  src/components/learnDetail/VideoDetail/index.tsx
  src/components/learnDetail/VideoDetail/style.ts
Labels: 🪄 chore

#110 [learn_detail] 학습 상세 페이지 ver.2 반영
  README.md
  public/assets/icons/ic_guide.svg
  public/assets/icons/ic_guide_clicked.svg
  public/assets/icons/ic_guide_hover.svg
  public/assets/icons/ic_x_button.svg
  public/assets/icons/index.ts
  src/components/common/NavigationBar.tsx
  src/components/learnDetail/VideoDetail.tsx
  src/components/learnDetail/memo/MemoList.tsx
  src/pages/learn/[id].tsx
Labels: 💅 design

#112 [learn_detail] x 버튼 로직 수정
  src/pages/learn/[id].tsx
Labels: 🐛 fix

#113 [learn_detail] 메모 관련 추가 작업
  public/assets/icons/ic_arrow_up.svg
  public/assets/icons/index.ts
  src/components/common/Footer.tsx
  src/components/common/Like.tsx
  src/components/learnDetail/ConfirmModal.tsx
  src/components/learnDetail/ContextMenu.tsx
  src/components/learnDetail/memo/Memo.tsx
  src/components/learnDetail/memo/MemoDotButton.tsx
  src/components/learnDetail/memo/MemoForm.tsx
  src/components/learnDetail/memo/MemoList.tsx
  src/components/learnDetail/memo/MemoPopup.tsx
  src/components/learnDetail/memo/MemoPopupButton.tsx
  src/pages/learn/[id].tsx
  src/services/mock/learn-detail.data.ts
  src/utils/constant.ts
Labels: 🐛 fix, 💅 design, ✨ feat, 🔨 refactor
