Repository DeliverBle/deliverble-frontend, pull requests merged in 2023-04, with the labels that each got.

#216 [home, learn_detail] 스피치 가이드 코드 리팩토링
  src/components/common/NewsList.tsx
  src/components/learnDetail/memo/MemoItem.tsx
  src/components/learnDetail/record/RecordLog.tsx
  src/components/learnDetail/speechGuide/LearningButton.tsx
  src/components/learnDetail/speechGuide/SpeechGuideTitle.tsx
  src/components/learnDetail/speechGuide/SpeechGuideTooltip.tsx
  src/components/learnDetail/speechGuide/index.ts
  src/hooks/useDeleteElement.ts
  src/pages/learn/[id].tsx
  src/stores/newsState.ts
  src/utils/constant.ts
Labels: 🔨 refactor

#217 [landing] 사파리 이슈 대응
  package.json
  public/assets/images/img_review_empty.svg
  public/assets/images/img_review_empty.webp
  public/assets/images/index.ts
  src/components/review/Empty.tsx
  src/hooks/useSlideObserver.ts
Labels: 🐛 fix

#225 [common] types 폴더 개선 및 constants 폴더 생성
  src/components/common/BannerSlider.tsx
  src/components/common/ErrorContent.tsx
  src/components/common/NewsList.tsx
  src/components/learn/SelectBox.tsx
  src/components/learnDetail/ContextMenu.tsx
  src/components/learnDetail/ScriptTitle.tsx
  src/components/learnDetail/StudyLog.tsx
  src/components/learnDetail/VideoDetail.tsx
  src/components/learnDetail/memo/MemoDotButton.tsx
  src/components/learnDetail/memo/MemoDropdown.tsx
  src/components/learnDetail/memo/MemoForm.tsx
  src/components/learnDetail/memo/MemoItem.tsx
  src/components/learnDetail/memo/MemoLog.tsx
  src/components/learnDetail/modal/ConfirmModal.tsx
  src/components/learnDetail/scriptEdit/ScriptEdit.tsx
  src/components/review/VideoContainer.tsx
  src/constants/common.ts
  src/constants/home.ts
  src/constants/learn.ts
  src/constants/learnDetail/index.ts
  src/constants/learnDetail/memo.ts
  src/constants/learnDetail/modal.ts
  src/hooks/learnDetail/useDeleteElement.ts
  src/hooks/learnDetail/useRightClickHandler.ts
  src/hooks/learnDetail/useUpdateMemoList.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/fallback.tsx
  src/pages/home.tsx
  src/pages/learn/[id].tsx
  src/pages/learn/index.tsx
  src/pages/review.tsx
  src/services/api/common.ts
  src/services/api/home.ts
  src/services/api/learn-detail.ts
  src/services/api/learn.ts
  src/services/api/review.ts
  src/services/remote/learn-detail.ts
  src/services/remote/learn.ts
  src/services/remote/review.ts
  src/types/common/remote.ts
  src/types/error.ts
  src/types/home/remote.ts
  src/types/learn/remote.ts
  src/types/learnDetail/index.ts
  src/types/learnDetail/remote.ts
  src/types/review/remote.ts
  src/utils/constant.ts
  src/utils/contextMenu.ts
  src/utils/underlineMemo.ts
Labels: 🎨 style, 🔨 refactor

#227 [common] 리액트 쿼리 적용 - 1
  package.json
  src/components/common/CustomErrorBoundary.tsx
  src/components/common/ErrorContent.tsx
  src/components/common/ProfileModal.tsx
  src/components/learnDetail/record/RecordDropdown.tsx
  src/components/learnDetail/record/RecordLog.tsx
  src/hooks/learnDetail/useDeleteElement.ts
  src/hooks/learnDetail/useUpdateMemoList.ts
  src/pages/_app.tsx
  src/pages/auth/callback/kakao.tsx
  src/pages/fallback.tsx
  src/pages/home.tsx
  src/pages/learn/[id].tsx
  src/pages/learn/index.tsx
  src/pages/review.tsx
  src/services/api/home.ts
  src/services/api/learn-detail.ts
  src/services/mock/common.data.ts
  src/services/mock/home.data.ts
  src/services/mock/learn-detail.ts
  src/services/queries/.gitkeep
  src/services/queries/common.ts
  src/services/queries/home.ts
  src/services/queries/learn-detail.ts
  src/services/queries/learn.ts
  src/services/queries/review.ts
  src/services/remote/base.ts
  src/services/remote/common.ts
  src/services/remote/home.ts
  src/services/remote/learn-detail.ts
  src/services/remote/learn.ts
  src/services/remote/review.ts
  src/types/common/remote.ts
  src/types/home/remote.ts
  src/types/learnDetail/remote.ts
  yarn.lock
Labels: 🎨 style, 🔨 refactor
